// Common UK universities for the onboarding datalist. This is a suggestion
// list only — the field stays free-text so anything not listed (overseas
// institutions, NHS trusts, etc.) can still be typed in manually.
export const UK_UNIVERSITIES = [
  "University of Aberdeen",
  "Anglia Ruskin University",
  "Aston University",
  "Bangor University",
  "University of Bath",
  "University of Birmingham",
  "University of Bristol",
  "Brunel University London",
  "University of Cambridge",
  "Cardiff University",
  "City, University of London",
  "University of Dundee",
  "Durham University",
  "University of East Anglia",
  "University of Edinburgh",
  "University of Exeter",
  "University of Glasgow",
  "Imperial College London",
  "Keele University",
  "King's College London",
  "Lancaster University",
  "University of Leeds",
  "University of Leicester",
  "University of Liverpool",
  "London School of Hygiene & Tropical Medicine",
  "University of Manchester",
  "Newcastle University",
  "University of Nottingham",
  "University of Oxford",
  "Plymouth University",
  "Queen Mary University of London",
  "Queen's University Belfast",
  "University of Sheffield",
  "University of Southampton",
  "University of St Andrews",
  "St George's, University of London",
  "Swansea University",
  "University College London",
  "University of Warwick",
  "University of York",
] as const;
